name: Tests
on: [push]
jobs:
  jinjasql:
    name: JinjaSQL Tests
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: squealy-core
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Unit Tests
        working-directory: squealy-core
        run: python run_tests
      